version: '3'

services:

  web:
    build:
      context: ./php
      args: 
        PHP_VERSION: ${PHP_VERSION}
    volumes:
      - ${PHP_INI}:/etc/php.ini
      - ${APP_CODE_PATH}:/var/www/html
    domainname: ${DOMAIN_NAME}
    ports:
      - ${WEB_PORT}:80
    links:
      - db

  db:
    image: mysql:${MYSQL_VERSION}
    volumes:
      - ${MYSQL_DATA}:/var/lib/mysql
      - ${MYSQL_ENTRYPOINT_INITDB}:/docker-entrypoint-initdb.d
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      TZ: ${WORKSPACE_TIMEZONE}
    ports:
      - ${MYSQL_PORT}:3306

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    volumes:
      - ${PHPMYADMIN_SESSIONS}:/sessions
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=db
      - PMA_USER=${MYSQL_USER}
      - PMA_PASSWORD=${MYSQL_PASSWORD}
    domainname: ${DOMAIN_NAME}
    ports:
      - ${PHPMYADMIN_PORT}:80
    links:
      - db
